//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab0302_Data_Binding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string student_id { get; set; }
        public string student_fulname { get; set; }
        public byte[] student_image { get; set; }
        public string student_pssword { get; set; }
        public Nullable<System.DateTime> student_birthday { get; set; }
    }
}
